### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by clauseggers** [chrisyip/language-opentype#11]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `language-opentype` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app/src/package.js:433:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app/src/package.js:444:32)
```

**Comment by chrisyip** [comment]
Because of Atom changed stylesheet loading behavior, `stylesheets` is removed.

Thanks.
